// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "multi_in0_V"
#define AUTOTB_TVIN_multi_in0_V  "../tv/cdatafile/c.multi_apuint.autotvin_multi_in0_V.dat"
// wrapc file define: "multi_in1_V"
#define AUTOTB_TVIN_multi_in1_V  "../tv/cdatafile/c.multi_apuint.autotvin_multi_in1_V.dat"
// wrapc file define: "multi_out_V"
#define AUTOTB_TVOUT_multi_out_V  "../tv/cdatafile/c.multi_apuint.autotvout_multi_out_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "multi_out_V"
#define AUTOTB_TVOUT_PC_multi_out_V  "../tv/rtldatafile/rtl.multi_apuint.autotvout_multi_out_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			multi_in0_V_depth = 0;
			multi_in1_V_depth = 0;
			multi_out_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{multi_in0_V " << multi_in0_V_depth << "}\n";
			total_list << "{multi_in1_V " << multi_in1_V_depth << "}\n";
			total_list << "{multi_out_V " << multi_out_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int multi_in0_V_depth;
		int multi_in1_V_depth;
		int multi_out_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void multi_apuint (
ap_uint<8> multi_in0,
ap_uint<8> multi_in1,
ap_uint<16>* multi_out);

void AESL_WRAP_multi_apuint (
ap_uint<8> multi_in0,
ap_uint<8> multi_in1,
ap_uint<16>* multi_out)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "multi_out_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_multi_out_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_multi_out_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_multi_out_V, AESL_token); // data

			sc_bv<16> *multi_out_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'multi_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'multi_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					multi_out_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_multi_out_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_multi_out_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: multi_out_V
				{
					// bitslice(15, 0)
					// {
						// celement: multi_out.V(15, 0)
						// {
							sc_lv<16>* multi_out_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: multi_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(multi_out[0]) != NULL) // check the null address if the c port is array or others
								{
									multi_out_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(multi_out_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: multi_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : multi_out[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : multi_out[0]
								// output_left_conversion : multi_out[i_0]
								// output_type_conversion : (multi_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(multi_out[0]) != NULL) // check the null address if the c port is array or others
								{
									multi_out[i_0] = (multi_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] multi_out_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "multi_in0_V"
		char* tvin_multi_in0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_multi_in0_V);

		// "multi_in1_V"
		char* tvin_multi_in1_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_multi_in1_V);

		// "multi_out_V"
		char* tvout_multi_out_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_multi_out_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_multi_in0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_multi_in0_V, tvin_multi_in0_V);

		sc_bv<8> multi_in0_V_tvin_wrapc_buffer;

		// RTL Name: multi_in0_V
		{
			// bitslice(7, 0)
			{
				// celement: multi_in0.V(7, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : multi_in0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : multi_in0
						// regulate_c_name       : multi_in0_V
						// input_type_conversion : (multi_in0).to_string(2).c_str()
						if (&(multi_in0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> multi_in0_V_tmp_mem;
							multi_in0_V_tmp_mem = (multi_in0).to_string(2).c_str();
							multi_in0_V_tvin_wrapc_buffer.range(7, 0) = multi_in0_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_multi_in0_V, "%s\n", (multi_in0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_multi_in0_V, tvin_multi_in0_V);
		}

		tcl_file.set_num(1, &tcl_file.multi_in0_V_depth);
		sprintf(tvin_multi_in0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_multi_in0_V, tvin_multi_in0_V);

		// [[transaction]]
		sprintf(tvin_multi_in1_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_multi_in1_V, tvin_multi_in1_V);

		sc_bv<8> multi_in1_V_tvin_wrapc_buffer;

		// RTL Name: multi_in1_V
		{
			// bitslice(7, 0)
			{
				// celement: multi_in1.V(7, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : multi_in1
						// sub_1st_elem          : 
						// ori_name_1st_elem     : multi_in1
						// regulate_c_name       : multi_in1_V
						// input_type_conversion : (multi_in1).to_string(2).c_str()
						if (&(multi_in1) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<8> multi_in1_V_tmp_mem;
							multi_in1_V_tmp_mem = (multi_in1).to_string(2).c_str();
							multi_in1_V_tvin_wrapc_buffer.range(7, 0) = multi_in1_V_tmp_mem.range(7, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_multi_in1_V, "%s\n", (multi_in1_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_multi_in1_V, tvin_multi_in1_V);
		}

		tcl_file.set_num(1, &tcl_file.multi_in1_V_depth);
		sprintf(tvin_multi_in1_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_multi_in1_V, tvin_multi_in1_V);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		multi_apuint(multi_in0, multi_in1, multi_out);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_multi_out_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_multi_out_V, tvout_multi_out_V);

		sc_bv<16>* multi_out_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: multi_out_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: multi_out.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : multi_out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : multi_out[0]
						// regulate_c_name       : multi_out_V
						// input_type_conversion : (multi_out[i_0]).to_string(2).c_str()
						if (&(multi_out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> multi_out_V_tmp_mem;
							multi_out_V_tmp_mem = (multi_out[i_0]).to_string(2).c_str();
							multi_out_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = multi_out_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_multi_out_V, "%s\n", (multi_out_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_multi_out_V, tvout_multi_out_V);
		}

		tcl_file.set_num(1, &tcl_file.multi_out_V_depth);
		sprintf(tvout_multi_out_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_multi_out_V, tvout_multi_out_V);

		// release memory allocation
		delete [] multi_out_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "multi_in0_V"
		delete [] tvin_multi_in0_V;
		// release memory allocation: "multi_in1_V"
		delete [] tvin_multi_in1_V;
		// release memory allocation: "multi_out_V"
		delete [] tvout_multi_out_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

