// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_multi_apuint (
ap_uint<8> multi_in0,
ap_uint<8> multi_in1,
ap_uint<16>* multi_out);
